### ISSUE TITLE
Cannot get /user/profile in v3.0.0

### ISSUE THREAD

**Issue by pdbreen** [amzn/amazon-pay-sdk-php#43] opened 2017-03-28 18:16 UTC
Authorization: bearer header added by HttpCurl::httpGet()  is overwritten by HttpCurl::execute() method.  As a result, attempts to get /user/profile detail end of with a 400 / malformed request result.

Pull request to follow.

**Comment by bjguillot** [comment] 2017-03-28 23:07
Thanks for your contribution.  We are reviewing your pull request.

**Comment by bjguillot** [comment] 2019-08-05 14:26
Merged the PR back in 2017 but never closed out the issue issue.  This was incorporated in version 3.1.0 back in May 2017.

**Closed by bjguillot** 2019-08-05 14:26 UTC
